<p align="center"><font size="6"><b>Notebook de Charles-Henri SAINT-MARS</b></font></p>

# **NumPy**

## N-dimensional array (ndarray)

Un `ndarray` (abréviation de N-dimensional array) est la structure de données principale dans la bibliothèque NumPy. C'est un tableau multidimensionnel d'éléments de même type, permettant des opérations rapides et efficaces sur des ensembles de données numériques.

Voici quelques points clés à propos des `ndarray` :

Caractéristiques d'un `ndarray` :
Dimensionnalité : Comme son nom l'indique, un `ndarray` peut avoir un nombre arbitraire de dimensions. Un tableau à 1 dimension est équivalent à une liste Python, un tableau à 2 dimensions peut être vu comme une matrice, et un tableau à N dimensions est plus général.

Homogénéité des données : Tous les éléments d'un `ndarray` sont du même type de données (par exemple, tous des entiers, des flottants, etc.). Cela permet d'optimiser les opérations et l'utilisation de la mémoire.

Attributs importants :

`ndarray.shape` : Renvoie une tuple décrivant les dimensions du tableau (nombre de lignes, colonnes, etc.). <br>
`ndarray.ndim` : Renvoie le nombre de dimensions du tableau. <br>
`ndarray.size` : Renvoie le nombre total d'éléments dans le tableau. <br>
`ndarray.dtype` : Indique le type des éléments du tableau (ex. int32, float64, etc.).

**Différence avec les listes Python :** <br>
Contrairement aux listes Python, un `ndarray` est plus performant pour des calculs mathématiques et des opérations sur de grandes quantités de données grâce à l'utilisation de types homogènes et de structures mémoire contiguës.

En résumé, un `ndarray` est une structure optimisée pour les opérations scientifiques et numériques dans Python, idéale pour manipuler des tableaux de données multidimensionnels.

In [1]:
import numpy as np

In [2]:
notre_tableau = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 , 15, 16, 17, 18, 19, 20])
print(notre_tableau) 
print(notre_tableau[3])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
4


In [3]:
mon_tableau_bidimensionnel = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(mon_tableau_bidimensionnel)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# La vue d'un tableau
sous_tableau = notre_tableau[0:5] # index de 0 à 4
print("sous_tableau: ", sous_tableau)
sous_tableau[0] = 10
print("sous_tableau modifié: ", sous_tableau)
print("notre_tableau modifié également: ", notre_tableau)

sous_tableau:  [1 2 3 4 5]
sous_tableau modifié:  [10  2  3  4  5]
notre_tableau modifié également:  [10  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [5]:
# La copie partielle d'un tableau
notre_tableau = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 , 15, 16, 17, 18, 19, 20])
copie_sous_tableau = notre_tableau[0:5].copy()
print("copie_sous_tableau: ", copie_sous_tableau)
copie_sous_tableau[0] = 10
print("copie_sous_tableau modifié: ", copie_sous_tableau)
print("notre_tableau non modifié: ", notre_tableau)

copie_sous_tableau:  [1 2 3 4 5]
copie_sous_tableau modifié:  [10  2  3  4  5]
notre_tableau non modifié:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [6]:
# Accès à un élément d'un tableau bidimensionnel
mon_tableau_bidimensionnel[1,2] # deuxième ligne, troisième colonne
# Pour accéder à l'élément 6, on écrit mon_tableau_bidimensionnel[1,2] où 1 est l'index de la ligne et 2 est l'index de la colonne de l'élément 6.
# Le index des lignes et des colonnes comment à partir de 0.

# Deuxième manière d'accéder à un élément d'un tableau bidimensionnel
# mon_tableau_bidimensionnel[1][2]

6

In [7]:
# Accès à un élément d'un tableau bidimensionnel avec des indices négatifs
mon_tableau_bidimensionnel[1,-1] # deuxième ligne, dernière colonne

6

In [8]:
# Afficher toutes les lignes de la première colonne en utilisant le slicing
print(mon_tableau_bidimensionnel[:,0]) # : signifie toutes les lignes
# On peut voir les : comme un raccourci pour dire "du début jusqu'à la fin de l'ensemble des lignes".

[1 4 7]


In [9]:
# Afficher toutes les colonnes de la deuxième ligne en utilisant le slicing
print(mon_tableau_bidimensionnel[1,:]) # : signifie toutes les colonnes

[4 5 6]


In [10]:
# Afficher toutes les lignes d'une part et les colonnes avec un pas de 2 d'autre part
print(mon_tableau_bidimensionnel[::,::2])


[[1 3]
 [4 6]
 [7 9]]


In [11]:
# Afficher toutes lignes de la dernière colonne en utilisant un index négatif
print(mon_tableau_bidimensionnel[:,-1])

[3 6 9]


In [12]:
print(mon_tableau_bidimensionnel[:,1:-1]) # toutes les lignes, de la deuxième colonne à l'avant dernière colonne
# -1 est l'index de la fin dans le slicing donc il est exclusif. Cela revient à désigner l'avant dernière colonne (index -2).

[[2]
 [5]
 [8]]


In [13]:
# Afficher la dernière ligne et la deuxième colonne en utilisant le slicing
print(mon_tableau_bidimensionnel[-1,1:-1])

# Deuxième manière d'accéder à la dernière ligne et la deuxième colonne
print(mon_tableau_bidimensionnel[-1,1:2])

[8]
[8]


In [14]:
# Créer une matrice de 6 x 4 avec des nombres aléatoires à l'aide de la fonction randint() de numpy.
# Les valeurs vont de 0 à 100 (0 est inclusif et 100 est exclusif).
matrice = np.random.randint(0, 100, (6, 4))
print(matrice)

[[ 3 60 87 14]
 [76 31 95  4]
 [83 80 62 36]
 [18 64 15 30]
 [54 82 53 69]
 [40  0 87 69]]


### Les attribut d'un ndarray (N-dimensional array)

In [15]:
matrice.ndim # nombre de dimensions

2

In [16]:
matrice.shape # forme de la matrice

(6, 4)

In [17]:
matrice.dtype # type des éléments de la matrice

dtype('int32')

In [18]:
matrice.size # nombre total d'éléments dans la matrice

24

In [19]:
matrice[matrice > 50] # sélectionner les éléments de la matrice qui sont supérieurs à 50

array([60, 87, 76, 95, 83, 80, 62, 64, 54, 82, 53, 69, 87, 69])

In [20]:
matrice > 50 # renvoie un tableau de booléens

array([[False,  True,  True, False],
       [ True, False,  True, False],
       [ True,  True,  True, False],
       [False,  True, False, False],
       [ True,  True,  True,  True],
       [False, False,  True,  True]])

Ce qui est True pour matrice > 50 est affiché et ce qui est False n'est pas affiché

In [21]:
matrice[(matrice >= 50) & (matrice <= 70)] # sélectionner les éléments de la matrice qui sont supérieurs ou égaux à 50 et inférieurs ou égaux à 70

array([60, 62, 64, 54, 53, 69, 69])

In [22]:
matrice[(matrice >=50 ) | (matrice <= 30)]  # sélectionner les éléments de la matrice qui sont supérieurs ou égaux à 50 ou inférieurs ou égaux à 30

array([ 3, 60, 87, 14, 76, 95,  4, 83, 80, 62, 18, 64, 15, 30, 54, 82, 53,
       69,  0, 87, 69])

In [23]:
# Concaténation de tableaux
tableau1 = np.array([[1, 2, 3], [4, 5, 6]])
tableau2 = np.array([[7, 8, 9], [10, 11, 12]])
tableau3 = np.concatenate([tableau1, tableau2], axis=0) # concaténation verticale
print(tableau3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [24]:
# Concaténation horizontale de tableaux
tableau4 = np.concatenate([tableau1, tableau2], axis=1) # concaténation horizontale
print(tableau4)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [25]:
# Concaténation de tableaux de dimensions différentes
tableau5 = np.array([1, 2, 3])
tableau6 = np.array([[4, 5, 6], [7, 8, 9], [10, 11, 12]])
tableau7 = np.vstack([tableau5, tableau6]) # concaténation verticale
print(tableau7)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [26]:
# Concaténation horizontale de tableaux de dimensions différentes
tableau8 = np.hstack([tableau6, tableau5.reshape(3,1)]) # concaténation horizontale
print(tableau8)

[[ 4  5  6  1]
 [ 7  8  9  2]
 [10 11 12  3]]


In [27]:
 # Créer un tableau de 10 éléments
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
len(array) # longueur du tableau : 10
array1, array2, array3 = np.split(array, [2, 6]) # découper le tableau en trois parties
# 2 est l'index du début de la première découpe et 6 est l'index du début de la deuxième découpe.
print(array1, array2, array3)

[1 2] [3 4 5 6] [ 7  8  9 10]


In [28]:
# Créer un tableau bidimensionnel
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
# Axes de découpe
# axis = 0 # axe des index des lignes (dit aussi vertical car les index des lignes sont sur l'axe vertical)
# axis = 1 # axe des index des colonnes (dit aussi horizontal car les index des colonnes sont sur l'axe horizontal)

In [30]:
# Découper le tableau en deux parties selon l'axe 0 (vertical)
array1, array2 = np.vsplit(array, [2]) # [2] est l'index de la première ligne de la deuxième partie
print("array1 : ")
print(array1)
print("")
print("array2 : ")
print(array2)

array1 : 
[[1 2 3 4]
 [5 6 7 8]]

array2 : 
[[ 9 10 11 12]]


In [31]:
# Découper le tableau en deux parties selon l'axe 1 (horizontal)
array1, array2 = np.hsplit(array, [2]) # [2] est l'index de la première colonne de la deuxième partie
print("array1 : ")
print(array1)
print("")
print("array2 : ")
print(array2)

array1 : 
[[ 1  2]
 [ 5  6]
 [ 9 10]]

array2 : 
[[ 3  4]
 [ 7  8]
 [11 12]]


### Opérations arithmétiques sur les tableaux

In [32]:
 # Créer tableau aléatoire de 10 lignes et 9 colonnes avec des valeurs comprises entre 0 et 350 (avec 350 exclus)
array = np.random.randint(350, size=(10, 9))
print(array)

[[188 254 275 243  82 127 221 267  85]
 [104 302  45 280 330 251  99 323 240]
 [170  99  91 146 336 155  12 176 204]
 [332 122 227  26 330  44 137 137  72]
 [137 162 248 338 257  91 195  79 276]
 [ 29  61 189  11 195 323 323 108  17]
 [336 166 110 248  16 273  19 181 103]
 [210  70  42 253 309 103 304 244  21]
 [ 16 119 255 106 328 248 344 309  17]
 [322 317  26  47  16 315  12 217  29]]


In [33]:
array + 2 # ajouter 2 à chaque élément du tableau

array([[190, 256, 277, 245,  84, 129, 223, 269,  87],
       [106, 304,  47, 282, 332, 253, 101, 325, 242],
       [172, 101,  93, 148, 338, 157,  14, 178, 206],
       [334, 124, 229,  28, 332,  46, 139, 139,  74],
       [139, 164, 250, 340, 259,  93, 197,  81, 278],
       [ 31,  63, 191,  13, 197, 325, 325, 110,  19],
       [338, 168, 112, 250,  18, 275,  21, 183, 105],
       [212,  72,  44, 255, 311, 105, 306, 246,  23],
       [ 18, 121, 257, 108, 330, 250, 346, 311,  19],
       [324, 319,  28,  49,  18, 317,  14, 219,  31]])

In [34]:
print(array)

[[188 254 275 243  82 127 221 267  85]
 [104 302  45 280 330 251  99 323 240]
 [170  99  91 146 336 155  12 176 204]
 [332 122 227  26 330  44 137 137  72]
 [137 162 248 338 257  91 195  79 276]
 [ 29  61 189  11 195 323 323 108  17]
 [336 166 110 248  16 273  19 181 103]
 [210  70  42 253 309 103 304 244  21]
 [ 16 119 255 106 328 248 344 309  17]
 [322 317  26  47  16 315  12 217  29]]


In [35]:
array - 2 # soustraire 2 à chaque élément du tableau

array([[186, 252, 273, 241,  80, 125, 219, 265,  83],
       [102, 300,  43, 278, 328, 249,  97, 321, 238],
       [168,  97,  89, 144, 334, 153,  10, 174, 202],
       [330, 120, 225,  24, 328,  42, 135, 135,  70],
       [135, 160, 246, 336, 255,  89, 193,  77, 274],
       [ 27,  59, 187,   9, 193, 321, 321, 106,  15],
       [334, 164, 108, 246,  14, 271,  17, 179, 101],
       [208,  68,  40, 251, 307, 101, 302, 242,  19],
       [ 14, 117, 253, 104, 326, 246, 342, 307,  15],
       [320, 315,  24,  45,  14, 313,  10, 215,  27]])

In [36]:
array * 2 # multiplier chaque élément du tableau par 2 

array([[376, 508, 550, 486, 164, 254, 442, 534, 170],
       [208, 604,  90, 560, 660, 502, 198, 646, 480],
       [340, 198, 182, 292, 672, 310,  24, 352, 408],
       [664, 244, 454,  52, 660,  88, 274, 274, 144],
       [274, 324, 496, 676, 514, 182, 390, 158, 552],
       [ 58, 122, 378,  22, 390, 646, 646, 216,  34],
       [672, 332, 220, 496,  32, 546,  38, 362, 206],
       [420, 140,  84, 506, 618, 206, 608, 488,  42],
       [ 32, 238, 510, 212, 656, 496, 688, 618,  34],
       [644, 634,  52,  94,  32, 630,  24, 434,  58]])

In [37]:
array[:,0] * 10 # multiplier la première colonne par 10

array([1880, 1040, 1700, 3320, 1370,  290, 3360, 2100,  160, 3220])

In [38]:
print(array)

[[188 254 275 243  82 127 221 267  85]
 [104 302  45 280 330 251  99 323 240]
 [170  99  91 146 336 155  12 176 204]
 [332 122 227  26 330  44 137 137  72]
 [137 162 248 338 257  91 195  79 276]
 [ 29  61 189  11 195 323 323 108  17]
 [336 166 110 248  16 273  19 181 103]
 [210  70  42 253 309 103 304 244  21]
 [ 16 119 255 106 328 248 344 309  17]
 [322 317  26  47  16 315  12 217  29]]


In [39]:
array / 2 # diviser chaque élément du tableau par 2

array([[ 94. , 127. , 137.5, 121.5,  41. ,  63.5, 110.5, 133.5,  42.5],
       [ 52. , 151. ,  22.5, 140. , 165. , 125.5,  49.5, 161.5, 120. ],
       [ 85. ,  49.5,  45.5,  73. , 168. ,  77.5,   6. ,  88. , 102. ],
       [166. ,  61. , 113.5,  13. , 165. ,  22. ,  68.5,  68.5,  36. ],
       [ 68.5,  81. , 124. , 169. , 128.5,  45.5,  97.5,  39.5, 138. ],
       [ 14.5,  30.5,  94.5,   5.5,  97.5, 161.5, 161.5,  54. ,   8.5],
       [168. ,  83. ,  55. , 124. ,   8. , 136.5,   9.5,  90.5,  51.5],
       [105. ,  35. ,  21. , 126.5, 154.5,  51.5, 152. , 122. ,  10.5],
       [  8. ,  59.5, 127.5,  53. , 164. , 124. , 172. , 154.5,   8.5],
       [161. , 158.5,  13. ,  23.5,   8. , 157.5,   6. , 108.5,  14.5]])

### Les méthodes de Numpy pour les opérations arithmétiques

In [40]:
# Ajouter 2 à chaque élément du tableau en utilisant la méthode add() de numpy
np.add(array, 2) 

array([[190, 256, 277, 245,  84, 129, 223, 269,  87],
       [106, 304,  47, 282, 332, 253, 101, 325, 242],
       [172, 101,  93, 148, 338, 157,  14, 178, 206],
       [334, 124, 229,  28, 332,  46, 139, 139,  74],
       [139, 164, 250, 340, 259,  93, 197,  81, 278],
       [ 31,  63, 191,  13, 197, 325, 325, 110,  19],
       [338, 168, 112, 250,  18, 275,  21, 183, 105],
       [212,  72,  44, 255, 311, 105, 306, 246,  23],
       [ 18, 121, 257, 108, 330, 250, 346, 311,  19],
       [324, 319,  28,  49,  18, 317,  14, 219,  31]])

In [41]:
# Retrancher 2 à chaque élément du tableau en utilisant la méthode subtract() de numpy
np.subtract(array, 2)

array([[186, 252, 273, 241,  80, 125, 219, 265,  83],
       [102, 300,  43, 278, 328, 249,  97, 321, 238],
       [168,  97,  89, 144, 334, 153,  10, 174, 202],
       [330, 120, 225,  24, 328,  42, 135, 135,  70],
       [135, 160, 246, 336, 255,  89, 193,  77, 274],
       [ 27,  59, 187,   9, 193, 321, 321, 106,  15],
       [334, 164, 108, 246,  14, 271,  17, 179, 101],
       [208,  68,  40, 251, 307, 101, 302, 242,  19],
       [ 14, 117, 253, 104, 326, 246, 342, 307,  15],
       [320, 315,  24,  45,  14, 313,  10, 215,  27]])

In [42]:
# Multiplier par 2 chaque élément du tableau en utilisant la méthode multiply() de numpy
np.multiply(array, 2)

array([[376, 508, 550, 486, 164, 254, 442, 534, 170],
       [208, 604,  90, 560, 660, 502, 198, 646, 480],
       [340, 198, 182, 292, 672, 310,  24, 352, 408],
       [664, 244, 454,  52, 660,  88, 274, 274, 144],
       [274, 324, 496, 676, 514, 182, 390, 158, 552],
       [ 58, 122, 378,  22, 390, 646, 646, 216,  34],
       [672, 332, 220, 496,  32, 546,  38, 362, 206],
       [420, 140,  84, 506, 618, 206, 608, 488,  42],
       [ 32, 238, 510, 212, 656, 496, 688, 618,  34],
       [644, 634,  52,  94,  32, 630,  24, 434,  58]])

In [43]:
# Diviser par 2 chaque élément du tableau en utilisant la méthode divide() de numpy
np.divide(array, 2)

array([[ 94. , 127. , 137.5, 121.5,  41. ,  63.5, 110.5, 133.5,  42.5],
       [ 52. , 151. ,  22.5, 140. , 165. , 125.5,  49.5, 161.5, 120. ],
       [ 85. ,  49.5,  45.5,  73. , 168. ,  77.5,   6. ,  88. , 102. ],
       [166. ,  61. , 113.5,  13. , 165. ,  22. ,  68.5,  68.5,  36. ],
       [ 68.5,  81. , 124. , 169. , 128.5,  45.5,  97.5,  39.5, 138. ],
       [ 14.5,  30.5,  94.5,   5.5,  97.5, 161.5, 161.5,  54. ,   8.5],
       [168. ,  83. ,  55. , 124. ,   8. , 136.5,   9.5,  90.5,  51.5],
       [105. ,  35. ,  21. , 126.5, 154.5,  51.5, 152. , 122. ,  10.5],
       [  8. ,  59.5, 127.5,  53. , 164. , 124. , 172. , 154.5,   8.5],
       [161. , 158.5,  13. ,  23.5,   8. , 157.5,   6. , 108.5,  14.5]])

### Les méthodes de Numpy pour les calculs statistiques

In [44]:
print(np.mean(array)) # moyenne des éléments du tableau
print(array.mean()) # moyenne des éléments du tableau

173.57777777777778
173.57777777777778


In [45]:
# Calculer la moyenne par colonne
print(np.mean(array, axis=0))

[184.4 167.2 150.8 169.8 219.9 193.  166.6 204.1 106.4]


In [46]:
# Calculer la moyenne par ligne
print(np.mean(array, axis=1))

[193.55555556 219.33333333 154.33333333 158.55555556 198.11111111
 139.55555556 161.33333333 172.88888889 193.55555556 144.55555556]


In [47]:
print(np.median(array)) # médiane des éléments du tableau

173.0


In [48]:
print(np.std(array)) # écart-type des éléments du tableau

108.3665567289279


In [49]:
print(np.sum(array)) # somme des éléments du tableau

15622


In [50]:
print(array.min()) # élément minimum du tableau
print(array.max()) # élément maximum du tableau

11
344


In [51]:
# Calculer la variance des éléments du tableau
print(np.var(array))

11743.31061728395


In [52]:
np.sqrt(np.var(array)) # écart-type des éléments du tableau (racine carrée de la variance)

108.3665567289279

In [53]:
print(np.percentile(array, 25)) # premier quartile des éléments du tableau

82.75


In [54]:
print(np.percentile(array, 50)) # deuxième quartile des éléments du tableau (médiane)

173.0


In [55]:
print(np.percentile(array, 75)) # troisième quartile des éléments du tableau

264.5


In [56]:
print(np.percentile(array, 90)) # neuvième décile des éléments du tableau

323.0


## <font color="red">Problème à résoudre de la capsule 41</font>

**Objectif : Manipuler un array contenant les prix de vente de 20 maisons vendues en 2008 dans une petite ville du Midwest**
1. Importer les données au format array à partir du fichier houses.csv
2. Convertir le prix des maisons en euros, sachant que 1 dollar = 0.86 euros
3. Convertir les pieds carrés en mètres carrés, sachant que 1 pied carré = 0.09 m². 
4. Combien de maisons ont un terrain de plus de 1000 m²?
5. Calculer la somme totale obtenue après la vente des 20 maisons.
6. Quelle est la taille de la maison vendue la plus chère ?
7. Juste pour l’exercice, splitter (casser) l’array en trois tableaux, puis les concaténer à nouveau pour obtenir le tableau initial.

In [57]:
# 1. importation du fichier csv
houses = np.genfromtxt('Houses.csv', delimiter=',', dtype=int)
help(np.genfromtxt)

Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes', *, ndmin=0, like=None)
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
        that generators must retu

In [58]:
houses

array([[212000,   4148,  25264],
       [230000,   2501,  11891],
       [339000,   4374,  25351],
       [289000,   2398,  22215],
       [160000,   2536,   9234],
       [ 85000,   2368,  13329],
       [ 85000,   1264,   8407],
       [145000,   1572,  12588],
       [164000,   2375,  16204],
       [123500,   1161,   9626],
       [180000,   1542,   8755],
       [159500,   1464,  14636],
       [156000,   2240,  21780],
       [146500,   1269,  11250],
       [101500,    924,   7361],
       [109800,    768,  10497],
       [182000,   1320,  15768],
       [110000,   1845,  12153],
       [125000,   1274,  13634],
       [ 80000,   1905,  10890]])

In [59]:
dir(houses)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [60]:
houses.shape # forme de la matrice (nombre de lignes, nombre de colonnes)

(20, 3)

In [61]:
# La première colonne représente le prix de vente des maisons en dollars
# La deuxième colonne représente la surface de la maison en pieds carrés
# La troisième colonne représente la surface du terrain en pieds carrés
# 1 dolar = 0.86 euros
# 1 pied carré = 0.09 mètre carré


In [62]:
# 2. Convertir les prix des maisons en euros
houses[:,0] = houses[:,0] * 0.86
print(houses)

[[182320   4148  25264]
 [197800   2501  11891]
 [291540   4374  25351]
 [248540   2398  22215]
 [137600   2536   9234]
 [ 73100   2368  13329]
 [ 73100   1264   8407]
 [124700   1572  12588]
 [141040   2375  16204]
 [106210   1161   9626]
 [154800   1542   8755]
 [137170   1464  14636]
 [134160   2240  21780]
 [125990   1269  11250]
 [ 87290    924   7361]
 [ 94428    768  10497]
 [156520   1320  15768]
 [ 94600   1845  12153]
 [107500   1274  13634]
 [ 68800   1905  10890]]


In [63]:
# 3. Convertir les pieds carrés en mètres carrés, sachant que 1 pied carré = 0.09 m². 
houses[:,1] = houses[:,1] * 0.09
houses[:,2] = houses[:,2] * 0.09
print(houses)

[[182320    373   2273]
 [197800    225   1070]
 [291540    393   2281]
 [248540    215   1999]
 [137600    228    831]
 [ 73100    213   1199]
 [ 73100    113    756]
 [124700    141   1132]
 [141040    213   1458]
 [106210    104    866]
 [154800    138    787]
 [137170    131   1317]
 [134160    201   1960]
 [125990    114   1012]
 [ 87290     83    662]
 [ 94428     69    944]
 [156520    118   1419]
 [ 94600    166   1093]
 [107500    114   1227]
 [ 68800    171    980]]


In [64]:
# 4. Combien de maisons ont un terrain de plus de 1000 m² ?
terrains_plus_1000m2 = houses[houses[:,2] > 1000] # houses[surface_terrain > 1000]
print(terrains_plus_1000m2)
resultat = len(terrains_plus_1000m2) # nombre de listes imbriquées c-à-d le nombre de maisons
print("Le nombre de maisons qui ont un terrain de plus de 1000 m² est : ", resultat)


[[182320    373   2273]
 [197800    225   1070]
 [291540    393   2281]
 [248540    215   1999]
 [ 73100    213   1199]
 [124700    141   1132]
 [141040    213   1458]
 [137170    131   1317]
 [134160    201   1960]
 [125990    114   1012]
 [156520    118   1419]
 [ 94600    166   1093]
 [107500    114   1227]]
Le nombre de maisons qui ont un terrain de plus de 1000 m² est :  13


In [65]:
# 5. Calculer la somme totale obtenue après la vente des 20 maisons.
somme_totale = np.sum(houses[:,0])
print("La somme totale obtenue après la vente des 20 maisons est : ", somme_totale, "euros")

La somme totale obtenue après la vente des 20 maisons est :  2737208 euros


In [66]:
# 6. Quelle est la taille de la maison vendue la plus chère ?
taille_maison_plus_chere = np.max(houses[:,1])
print("La taille de la maison vendue la plus chère est : ", taille_maison_plus_chere, "m²")


La taille de la maison vendue la plus chère est :  393 m²


In [67]:
# Corrigé de la question précédente à savoir, 
# Quelle est la taille de la maison vendue la plus chère ?
index_prix_max = np.argmax(houses[:,0])
print("Index de la maison vendue la plus chère : ", index_prix_max)
taille_maison_plus_chere = houses[index_prix_max, 1]
print("La taille de la maison vendue la plus chère est : ", taille_maison_plus_chere, "m²")



Index de la maison vendue la plus chère :  2
La taille de la maison vendue la plus chère est :  393 m²


In [68]:
# 7. Splitter (casser) houses en trois tableaux selon l'axe 0
array1, array2, array3 = np.vsplit(houses, [6, 12]) # [6, 12] sont les index des premières lignes des deuxième et troisième parties
print("array1 : \n",array1) 
print("array2 : \n",array2)
print("array3 : \n",array3)


array1 : 
 [[182320    373   2273]
 [197800    225   1070]
 [291540    393   2281]
 [248540    215   1999]
 [137600    228    831]
 [ 73100    213   1199]]
array2 : 
 [[ 73100    113    756]
 [124700    141   1132]
 [141040    213   1458]
 [106210    104    866]
 [154800    138    787]
 [137170    131   1317]]
array3 : 
 [[134160    201   1960]
 [125990    114   1012]
 [ 87290     83    662]
 [ 94428     69    944]
 [156520    118   1419]
 [ 94600    166   1093]
 [107500    114   1227]
 [ 68800    171    980]]


In [69]:
# Concaténer array1, array2 et array3 à nouveau pour obtenir le tableau initial selon l'axe 0
houses_original = np.concatenate([array1, array2, array3], axis=0) # concaténation selon l'axe 0 (vertical)
print("houses_original : \n", houses_original)

houses_original : 
 [[182320    373   2273]
 [197800    225   1070]
 [291540    393   2281]
 [248540    215   1999]
 [137600    228    831]
 [ 73100    213   1199]
 [ 73100    113    756]
 [124700    141   1132]
 [141040    213   1458]
 [106210    104    866]
 [154800    138    787]
 [137170    131   1317]
 [134160    201   1960]
 [125990    114   1012]
 [ 87290     83    662]
 [ 94428     69    944]
 [156520    118   1419]
 [ 94600    166   1093]
 [107500    114   1227]
 [ 68800    171    980]]
